### ISSUE TITLE
Won't install on Krpyton

### ISSUE THREAD

**Issue by HenryHatten** [BigNoid/script.skinshortcuts#200] opened 2016-11-05 12:29 UTC
For Krypton I had to manually install script.module.unidecode first to get this (and the skin) to install:

[http://mirrors.kodi.tv/addons/krypton/script.module.unidecode/](http://mirrors.kodi.tv/addons/krypton/script.module.unidecode/)

**Comment by ghost** [comment] 2016-11-05 13:03
Are you able to install addons from the official repository generally? There are a few issues with recent Krypton builds whereby Kodi can't install addons which would lead to this issue. Otherwise a debug log would be needed.

**Comment by HenryHatten** [comment] 2016-11-06 13:23
Yes. From the debug log (not available anymore, overwritten) I got the message mentioning script.module.unidecode when I was trying to manually install script.skinshortcuts (which I was doing because Aeon Nox would not install). Installing script.module.unidecode manually allowed me then to install script.skinshortcuts without problems (and allowed me to install Aeon Nox successfully afterwards). Using Kodi 17.0 Beta 6 11.01.2016.

**Comment by ghost** [comment] 2016-11-06 16:52
I am unable to reproduce any issue installing Nox 5 on a clean Kodi nightly. Without a debug log I'm unable to do anything further, and this was most likely a Kodi or repo mirror problem as the unidecode module is available.

As such, I'm going to close this issue now, but if you are able to reproduce the problem and provide a debug log please feel free to re-open.

**Closed as completed by ghost** 2016-11-06 16:52 UTC
