### ISSUE TITLE
ready for deploy to stable ?

### ISSUE THREAD

**Issue by marcelveldt** [BigNoid/script.skinshortcuts#58] opened 2015-09-01 18:49 UTC
The current beta version has been tested by a bunch of users. Some issues found and fixed.
Now things seem to be very stable and this new version offers a lot of improvements.

Everybody happy with a deploy to the Kodi repo ?

**Comment by ghost** [comment] 2015-09-01 18:53
It's probably worth considering whether any of the fixes requested in #57 can go in before a push to stable - I'm not particularly familiar with the code in question, but some of the requests there (I'll go into detail in the PR itself) seem pretty straightforward and unlikely to causes breakages. Good to get them fixed before Tomer has to wait for another round of updates/beta's (however long that may take) before they get onto the repo?

For me, other than that, it's good to go (aside from removing 'Beta' notices from the changelog/readme). @Nessus85100 would be good to get approval from too :)

**Comment by marcelveldt** [comment] 2015-09-01 18:57
I already told Tomer that we're having a little feature freeze first to update the stable release before adding in any new features but if you're confident that that change won't break anything and you have time to look into it no problem to wait a few more days. It's just that the current beta has actually been tested by users. If we add something we should publish a new beta for a few days first.

Totally agree with getting the feedback from @Nessus85100 because he has tested the widget changes very well.

**Comment by ghost** [comment] 2015-09-01 18:59
Not something I'll look into soon as I'm not overly familiar with that code and I'm working primarily on other projects at the moment. (Actually not sure offhand, is it your code initially...?) I'm happy to wait until I or anyone else gets to it :)

**Comment by marcelveldt** [comment] 2015-09-01 19:00
Yeah, I've worked on that code a few weeks back so I'm familiar with it. I'll pick it up once the current release has been deployed on the Kodi repo.

**Comment by ghost** [comment] 2015-09-01 20:53
Just remembered one more thing that it's worth considering before a stable push - do you, @marcelveldt, want to consider adding the skin.helper widgets as default into the scripts overrides.xml widget-grouping? (With visibility condition to ensure they only display if the script is installed, of course...)

**Comment by Nessus85100** [comment] 2015-09-02 08:15
Yep, all working fine for me. I think we are good to go.

By the way, excellent work guys !!!

Cheers
Nessus

**Comment by BigNoid** [comment] 2015-09-02 08:21
Indeed, great work!  
I don't use many features of the script, but all is working fine in Nox.

**Comment by ghost** [comment] 2015-09-04 22:20
> Yep, all working fine for me. I think we are good to go.
> 
> Indeed, great work!
> 
> I don't use many features of the script, but all is working fine in Nox.

Thanks for the feedback. After so many updates to the fundamentals of the script, it's good to know its working for both skins that are using most features of the script, and skins that are using the original features before this script became ridiculously complex :)

**Comment by ghost** [comment] 2015-09-04 23:12
One final issue worth considering before committing this to stable (and a fairly simple change with little chance of breakage) based on a bug reported on the Kodi forums in the last couple of days - the script has the ability to enable debug logging for both itself and Kodi when an issue building or saving the menu occurs. However, it only does this if the debug log uploader script is installed. It may be worth changing this code so the debug logging is enabled whether or not the debug log uploader script is installed - this greatly increases the chances a useful log will be provided by the user.

**Comment by marcelveldt** [comment] 2015-09-04 23:44
Sounds good to me. Did you already check in that change ?

**Comment by ghost** [comment] 2015-09-04 23:46
TBH I'm not sure :) (I always drink on a Friday, and at this time of the evening I'm fairly confident I've made the changes, though I'd appreciate a second eye on the changes made, but I've honestly no idea whether the changes have been pushed or not - my local git client suggests they have been, but github.com doesn't seem to show them :)). Once I work out where the changes are, I'll ask you to take a look before they get merged :)

**Comment by ghost** [comment] 2015-09-04 23:55
I honestly can't see what's happened to that commit, so it's probably safe at this point to proceed as-is, and I'll sort it out properly when I have the time and the mental capacity to do so (it's been as-is for a while, keeping it as such won't affect feedback very much)

Edit: Looks like I pushed this before the merge, and so it got merged as part of, #60. Glad I found out where it got to :)

**Comment by ghost** [comment] 2015-09-05 04:37
Issue #62 to be confirmed as not a bug/fixed before any repo push. I'll do my best to confirm either way this weekend, if no-one beats me to it :)

Edit: Confirmed as issue with old version of skin.helper script installed, which didn't provide label, and nothing to stop repo push, though updated issue on forum with Just Select method (actually, looks like documentation error) may...

**Comment by ghost** [comment] 2015-09-05 06:44
Bug found @jurialmunkey with Just Select showNone/custom properties not being respected now fixed. Hopefully that's all before a repo push :)

**Comment by marcelveldt** [comment] 2015-09-05 07:07
OK! All great then. I'll submit the new version to the Kodi team this afternoon

**Comment by marcelveldt** [comment] 2015-09-05 13:08
I've sent the request to update the script on the repo. Once updated I'll publish the first version of the skin helper service on the rpeo.

**Comment by marcelveldt** [comment] 2015-09-18 16:38
Just pinged the Kodi team for the script's update on the repo. They might have missed my request.
@BigNoid did you inform Martijn that I can submit the updates ?

**Comment by marcelveldt** [comment] 2015-09-23 08:28
The script's update is now available on the Kodi repo.
@BigNoid discovered issues with Aeon Nox (and variants) on Helix because he had only changed Nox for Isengard so on the helix repo the script isn't updated (but has version 3.5.4) and for Isengard he bumped the version to 3.6.0 in order to resolve issues people were having:

Quote from email:

I am going to revert the update for Helix repo as that breaks the submenus for Aeon Nox and its mods. I am sure there's no skin yet on offical Helix repo that needs any features added in latest version, so this seems like the best fix atm.
This will bump the Helix version to 0.5.4 and Isengard to 0.6.0. I will sort this with a PR on skin shortcuts afterwards.

**Comment by BigNoid** [comment] 2015-09-23 08:49
@marcelveldt  See https://github.com/BigNoid/script.skinshortcuts/pull/70 for version bump + changelog fixup.

**Closed as completed** 2015-09-28 15:54 UTC
